### ISSUE TITLE
for some reason cannot run all the steps after "take/0/1" 

### ISSUE THREAD

**Issue by shootermv** [kentcdodds/ng2-random-user#1]
can see only "loading..." caption
the error i can see is "TypeError: Error loading "main" at http://localhost:9000/main.js(…)" and its leads to "zone.js" file

**Comment by kentcdodds** [comment]
I need to give you an apology. For some reason, I want watching this repository so I want getting notifications about issues and pull requests. I am so incredibly sorry. Please forgive me. I really feel awful. I hope my unresponsiveness doesn't hinder you contributing more in the future.

As for your specific issue, I'll give it a closer look soon.

**Comment by kentcdodds** [comment]
@shootermv, again, apologies for not getting to you sooner.

I would recommend that you find other material to learn Angular 2. This repository is ancient by Angular 2 standards and some stuff is definitely out of date. I wish you the best!

**Comment by shootermv** [comment]
No problems, thanks a lot
